return {
  "robitx/gp.nvim",
  config = function()
    local conf = {
      providers = {
        groq = {
          disable = false,
          endpoint = "https://api.groq.com/openai/v1/chat/completions",
          secret = os.getenv("GROQ_API_KEY"),
        },
        openai = {
          disable = true,
          endpoint = "https://api.openai.com/v1/chat/completions",
          -- secret = os.getenv("OPENAI_API_KEY"),
        },
      },
      agents = {
        {
          name = "ChatGroqLlama3.1-70B",
          provider = "groq",
          chat = true,
          command = false,
          -- string with model name or table with model name and parameters
          model = {
            model = "llama-3.1-70b-versatile",
            temperature = 0.6,
            top_p = 1,
            min_p = 0.05,
          },
          system_prompt = require("gp.defaults").chat_system_prompt,
        },
        {
          name = "CodeGroqLlama3.1-70B",
          provider = "groq",
          chat = false,
          command = true,
          model = {
            model = "llama-3.1-70b-versatile",
            temperature = 0.4,
            top_p = 1,
            min_p = 0.05,
          },
          system_prompt = require("gp.defaults").code_system_prompt,
        },
      },
    }
    require("gp").setup(conf)

    -- disable diagnostics for markdown
    vim.api.nvim_create_autocmd({ "BufEnter" }, {
      pattern = { vim.fn.expand("~/") .. ".local/share/nvim/gp/chats/*" },
      callback = function(event)
        local buf = event.buf
        vim.diagnostic.enable(false, { bufnr = buf })
      end,
    })
  end,
  cmd = {
    "GpChatNew",
    "GpChatPaste",
    "GpChatToggle",
    "GpChatFinder",
    "GpChatRespond",
    "GpChatDelete",
    "GpRewrite",
    "GpAppend",
    "GpPrepend",
    "GpEnew",
    "GpNew",
    "GpVnew",
    "GpTabnew",
    "GpPopup",
    "GpImplement",
    "GpContext",
  },
  keys = {
    {
      "<C-g><C-t>",
      ":<C-u>'<,'>GpChatNew tabnew<cr>",
      desc = "ChatNew tabnew",
      mode = "v",
      nowait = true,
      remap = false,
    },
    {
      "<C-g><C-v>",
      ":<C-u>'<,'>GpChatNew vsplit<cr>",
      desc = "ChatNew vsplit",
      mode = "v",
      nowait = true,
      remap = false,
    },
    {
      "<C-g><C-x>",
      ":<C-u>'<,'>GpChatNew split<cr>",
      desc = "ChatNew split",
      mode = "v",
      nowait = true,
      remap = false,
    },
    { "<C-g>a", ":<C-u>'<,'>GpAppend<cr>", desc = "Visual Append (after)", mode = "v", nowait = true, remap = false },
    {
      "<C-g>b",
      ":<C-u>'<,'>GpPrepend<cr>",
      desc = "Visual Prepend (before)",
      mode = "v",
      nowait = true,
      remap = false,
    },
    { "<C-g>c", ":<C-u>'<,'>GpChatNew<cr>", desc = "Visual Chat New", mode = "v", nowait = true, remap = false },
    { "<C-g>g", group = "generate into new ..", mode = "v", nowait = true, remap = false },
    { "<C-g>ge", ":<C-u>'<,'>GpEnew<cr>", desc = "Visual GpEnew", mode = "v", nowait = true, remap = false },
    { "<C-g>gn", ":<C-u>'<,'>GpNew<cr>", desc = "Visual GpNew", mode = "v", nowait = true, remap = false },
    { "<C-g>gp", ":<C-u>'<,'>GpPopup<cr>", desc = "Visual Popup", mode = "v", nowait = true, remap = false },
    { "<C-g>gt", ":<C-u>'<,'>GpTabnew<cr>", desc = "Visual GpTabnew", mode = "v", nowait = true, remap = false },
    { "<C-g>gv", ":<C-u>'<,'>GpVnew<cr>", desc = "Visual GpVnew", mode = "v", nowait = true, remap = false },
    { "<C-g>i", ":<C-u>'<,'>GpImplement<cr>", desc = "Implement selection", mode = "v", nowait = true, remap = false },
    { "<C-g>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent", mode = "v", nowait = true, remap = false },
    { "<C-g>p", ":<C-u>'<,'>GpChatPaste<cr>", desc = "Visual Chat Paste", mode = "v", nowait = true, remap = false },
    { "<C-g>r", ":<C-u>'<,'>GpRewrite<cr>", desc = "Visual Rewrite", mode = "v", nowait = true, remap = false },
    { "<C-g>s", "<cmd>GpStop<cr>", desc = "GpStop", mode = "v", nowait = true, remap = false },
    { "<C-g>t", ":<C-u>'<,'>GpChatToggle<cr>", desc = "Visual Toggle Chat", mode = "v", nowait = true, remap = false },
    { "<C-g>w", group = "Whisper", mode = "v", nowait = true, remap = false },
    { "<C-g>wa", ":<C-u>'<,'>GpWhisperAppend<cr>", desc = "Whisper Append", mode = "v", nowait = true, remap = false },
    {
      "<C-g>wb",
      ":<C-u>'<,'>GpWhisperPrepend<cr>",
      desc = "Whisper Prepend",
      mode = "v",
      nowait = true,
      remap = false,
    },
    { "<C-g>we", ":<C-u>'<,'>GpWhisperEnew<cr>", desc = "Whisper Enew", mode = "v", nowait = true, remap = false },
    { "<C-g>wn", ":<C-u>'<,'>GpWhisperNew<cr>", desc = "Whisper New", mode = "v", nowait = true, remap = false },
    { "<C-g>wp", ":<C-u>'<,'>GpWhisperPopup<cr>", desc = "Whisper Popup", mode = "v", nowait = true, remap = false },
    {
      "<C-g>wr",
      ":<C-u>'<,'>GpWhisperRewrite<cr>",
      desc = "Whisper Rewrite",
      mode = "v",
      nowait = true,
      remap = false,
    },
    { "<C-g>wt", ":<C-u>'<,'>GpWhisperTabnew<cr>", desc = "Whisper Tabnew", mode = "v", nowait = true, remap = false },
    { "<C-g>wv", ":<C-u>'<,'>GpWhisperVnew<cr>", desc = "Whisper Vnew", mode = "v", nowait = true, remap = false },
    { "<C-g>ww", ":<C-u>'<,'>GpWhisper<cr>", desc = "Whisper", mode = "v", nowait = true, remap = false },
    { "<C-g>x", ":<C-u>'<,'>GpContext<cr>", desc = "Visual GpContext", mode = "v", nowait = true, remap = false },
    -- normal mode mappings
    { "<C-g><C-t>", "<cmd>GpChatNew tabnew<cr>", desc = "New Chat tabnew", mode = "n", nowait = true, remap = false },
    { "<C-g><C-v>", "<cmd>GpChatNew vsplit<cr>", desc = "New Chat vsplit", mode = "n", nowait = true, remap = false },
    { "<C-g><C-x>", "<cmd>GpChatNew split<cr>", desc = "New Chat split", mode = "n", nowait = true, remap = false },
    { "<C-g>a", "<cmd>GpAppend<cr>", desc = "Append (after)", mode = "n", nowait = true, remap = false },
    { "<C-g>b", "<cmd>GpPrepend<cr>", desc = "Prepend (before)", mode = "n", nowait = true, remap = false },
    { "<C-g>c", "<cmd>GpChatNew<cr>", desc = "New Chat", mode = "n", nowait = true, remap = false },
    { "<C-g>f", "<cmd>GpChatFinder<cr>", desc = "Chat Finder", mode = "n", nowait = true, remap = false },
    { "<C-g>g", group = "generate into new ..", mode = "n", nowait = true, remap = false },
    { "<C-g>ge", "<cmd>GpEnew<cr>", desc = "GpEnew", mode = "n", nowait = true, remap = false },
    { "<C-g>gn", "<cmd>GpNew<cr>", desc = "GpNew", mode = "n", nowait = true, remap = false },
    { "<C-g>gp", "<cmd>GpPopup<cr>", desc = "Popup", mode = "n", nowait = true, remap = false },
    { "<C-g>gt", "<cmd>GpTabnew<cr>", desc = "GpTabnew", mode = "n", nowait = true, remap = false },
    { "<C-g>gv", "<cmd>GpVnew<cr>", desc = "GpVnew", mode = "n", nowait = true, remap = false },
    { "<C-g>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent", mode = "n", nowait = true, remap = false },
    { "<C-g>r", "<cmd>GpRewrite<cr>", desc = "Inline Rewrite", mode = "n", nowait = true, remap = false },
    { "<C-g>s", "<cmd>GpStop<cr>", desc = "GpStop", mode = "n", nowait = true, remap = false },
    { "<C-g>t", "<cmd>GpChatToggle<cr>", desc = "Toggle Chat", mode = "n", nowait = true, remap = false },
    { "<C-g>w", group = "Whisper", mode = "n", nowait = true, remap = false },
    {
      "<C-g>wa",
      "<cmd>GpWhisperAppend<cr>",
      desc = "Whisper Append (after)",
      mode = "n",
      nowait = true,
      remap = false,
    },
    {
      "<C-g>wb",
      "<cmd>GpWhisperPrepend<cr>",
      desc = "Whisper Prepend (before)",
      mode = "n",
      nowait = true,
      remap = false,
    },
    { "<C-g>we", "<cmd>GpWhisperEnew<cr>", desc = "Whisper Enew", mode = "n", nowait = true, remap = false },
    { "<C-g>wn", "<cmd>GpWhisperNew<cr>", desc = "Whisper New", mode = "n", nowait = true, remap = false },
    { "<C-g>wp", "<cmd>GpWhisperPopup<cr>", desc = "Whisper Popup", mode = "n", nowait = true, remap = false },
    {
      "<C-g>wr",
      "<cmd>GpWhisperRewrite<cr>",
      desc = "Whisper Inline Rewrite",
      mode = "n",
      nowait = true,
      remap = false,
    },
    { "<C-g>wt", "<cmd>GpWhisperTabnew<cr>", desc = "Whisper Tabnew", mode = "n", nowait = true, remap = false },
    { "<C-g>wv", "<cmd>GpWhisperVnew<cr>", desc = "Whisper Vnew", mode = "n", nowait = true, remap = false },
    { "<C-g>ww", "<cmd>GpWhisper<cr>", desc = "Whisper", mode = "n", nowait = true, remap = false },
    { "<C-g>x", "<cmd>GpContext<cr>", desc = "Toggle GpContext", mode = "n", nowait = true, remap = false },

    -- INSERT mode mappings
    { "<C-g><C-t>", "<cmd>GpChatNew tabnew<cr>", desc = "New Chat tabnew", mode = "i", nowait = true, remap = false },
    { "<C-g><C-v>", "<cmd>GpChatNew vsplit<cr>", desc = "New Chat vsplit", mode = "i", nowait = true, remap = false },
    { "<C-g><C-x>", "<cmd>GpChatNew split<cr>", desc = "New Chat split", mode = "i", nowait = true, remap = false },
    { "<C-g>a", "<cmd>GpAppend<cr>", desc = "Append (after)", mode = "i", nowait = true, remap = false },
    { "<C-g>b", "<cmd>GpPrepend<cr>", desc = "Prepend (before)", mode = "i", nowait = true, remap = false },
    { "<C-g>c", "<cmd>GpChatNew<cr>", desc = "New Chat", mode = "i", nowait = true, remap = false },
    { "<C-g>f", "<cmd>GpChatFinder<cr>", desc = "Chat Finder", mode = "i", nowait = true, remap = false },
    { "<C-g>g", group = "generate into new ..", mode = "i", nowait = true, remap = false },
    { "<C-g>ge", "<cmd>GpEnew<cr>", desc = "GpEnew", mode = "i", nowait = true, remap = false },
    { "<C-g>gn", "<cmd>GpNew<cr>", desc = "GpNew", mode = "i", nowait = true, remap = false },
    { "<C-g>gp", "<cmd>GpPopup<cr>", desc = "Popup", mode = "i", nowait = true, remap = false },
    { "<C-g>gt", "<cmd>GpTabnew<cr>", desc = "GpTabnew", mode = "i", nowait = true, remap = false },
    { "<C-g>gv", "<cmd>GpVnew<cr>", desc = "GpVnew", mode = "i", nowait = true, remap = false },
    { "<C-g>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent", mode = "i", nowait = true, remap = false },
    { "<C-g>r", "<cmd>GpRewrite<cr>", desc = "Inline Rewrite", mode = "i", nowait = true, remap = false },
    { "<C-g>s", "<cmd>GpStop<cr>", desc = "GpStop", mode = "i", nowait = true, remap = false },
    { "<C-g>t", "<cmd>GpChatToggle<cr>", desc = "Toggle Chat", mode = "i", nowait = true, remap = false },
    { "<C-g>w", group = "Whisper", mode = "i", nowait = true, remap = false },
    {
      "<C-g>wa",
      "<cmd>GpWhisperAppend<cr>",
      desc = "Whisper Append (after)",
      mode = "i",
      nowait = true,
      remap = false,
    },
    {
      "<C-g>wb",
      "<cmd>GpWhisperPrepend<cr>",
      desc = "Whisper Prepend (before)",
      mode = "i",
      nowait = true,
      remap = false,
    },
    { "<C-g>we", "<cmd>GpWhisperEnew<cr>", desc = "Whisper Enew", mode = "i", nowait = true, remap = false },
    { "<C-g>wn", "<cmd>GpWhisperNew<cr>", desc = "Whisper New", mode = "i", nowait = true, remap = false },
    { "<C-g>wp", "<cmd>GpWhisperPopup<cr>", desc = "Whisper Popup", mode = "i", nowait = true, remap = false },
    {
      "<C-g>wr",
      "<cmd>GpWhisperRewrite<cr>",
      desc = "Whisper Inline Rewrite",
      mode = "i",
      nowait = true,
      remap = false,
    },
    { "<C-g>wt", "<cmd>GpWhisperTabnew<cr>", desc = "Whisper Tabnew", mode = "i", nowait = true, remap = false },
    { "<C-g>wv", "<cmd>GpWhisperVnew<cr>", desc = "Whisper Vnew", mode = "i", nowait = true, remap = false },
    { "<C-g>ww", "<cmd>GpWhisper<cr>", desc = "Whisper", mode = "i", nowait = true, remap = false },
    { "<C-g>x", "<cmd>GpContext<cr>", desc = "Toggle GpContext", mode = "i", nowait = true, remap = false },
  },
}
